import sqlite3
import pandas as pd
import logging
from datetime import datetime, timedelta

class MLDataCollector:
    """
    Collects raw and composite signals generated by the AMT Engine,
    saves them to an SQLite database, and retroactively labels them
    with forward max excursions (MFE/MAE) or simple win/loss flags.
    """
    def __init__(self, db_path="amt_ml_dataset.db", look_forward_minutes=15):
        self.db_path = db_path
        self.look_forward_minutes = look_forward_minutes
        self.conn = sqlite3.connect(self.db_path, check_same_thread=False)
        self._create_tables()
        
    def _create_tables(self):
        cursor = self.conn.cursor()
        
        # Signals Table
        cursor.execute('''
        CREATE TABLE IF NOT EXISTS signals (
            id TEXT PRIMARY KEY,
            timestamp_event TEXT,
            asset TEXT,
            timeframe_secs INTEGER,
            signal_type TEXT,
            direction TEXT,
            is_composite BOOLEAN,
            trigger_price REAL,
            session_state TEXT,
            distance_to_poc_pct REAL,
            volume_zscore REAL,
            delta_zscore REAL,
            cvd_slope_short REAL,
            cvd_slope_long REAL,
            
            -- Labels (Updated retroactively)
            label_max_fwd_price REAL,
            label_min_fwd_price REAL,
            label_win_pct REAL,
            label_loss_pct REAL,
            is_labeled BOOLEAN DEFAULT 0
        )
        ''')
        self.conn.commit()

    def insert_signal(self, signal: dict):
        """
        Inserts a newly generated signal into the database.
        The label columns remain NULL until update_labels is called.
        """
        cursor = self.conn.cursor()
        
        # Extract features safely
        try:
            cursor.execute('''
            INSERT INTO signals (
                id, timestamp_event, asset, timeframe_secs, signal_type, direction, is_composite,
                trigger_price, session_state, distance_to_poc_pct, volume_zscore, delta_zscore,
                cvd_slope_short, cvd_slope_long
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            ''', (
                str(signal.get('id', 'unknown')),
                str(signal.get('timestamp_event')),
                str(signal.get('asset', 'unknown')),
                int(signal.get('timeframe_secs', 0)),
                str(signal.get('signal_type', 'unknown')),
                str(signal.get('direction', 'unknown')),
                bool(signal.get('is_composite', False)),
                float(signal.get('trigger_price', 0.0)),
                str(signal.get('session_state', 'unknown')),
                float(signal.get('distance_to_poc_pct', 0.0)),
                float(signal.get('volume_zscore', 0.0)),
                float(signal.get('delta_zscore', 0.0)),
                float(signal.get('cvd_slope_short', 0.0)),
                float(signal.get('cvd_slope_long', 0.0))
            ))
            self.conn.commit()
            logging.info(f"[MLDataCollector] 💾 Guardado novo sinal para treino: {signal.get('signal_type')} ({signal.get('direction')})")
        except sqlite3.IntegrityError:
            pass # Signal already exists
        except Exception as e:
            logging.error(f"[MLDataCollector] Erro ao gravar sinal no DB: {e}")

    def update_labels(self, current_time_iso: str, current_price: float, history_df: pd.DataFrame):
        """
        Scans for unlabeled signals that are older than `look_forward_minutes`.
        Calculates the max favorable excursion (MFE) and max adverse excursion (MAE)
        during that forward window and labels them.
        
        Args:
            current_time_iso: The current time of the simulation/live engine.
            current_price: The current price of the asset.
            history_df: The engine's historical candles DataFrame to look forward into.
        """
        try:
            # Always work with tz-naive datetimes internally
            current_dt = datetime.fromisoformat(current_time_iso.replace('Z', '').replace('+00:00', ''))
        except ValueError:
            return
            
        cursor = self.conn.cursor()
        
        # Find all signals that haven't been labeled yet
        cursor.execute("SELECT id, timestamp_event, trigger_price, direction FROM signals WHERE is_labeled = 0")
        unlabeled = cursor.fetchall()
        
        if not unlabeled or history_df.empty:
            return
            
        for row in unlabeled:
            sig_id, sig_time_str, trigger_price, direction = row
            try:
                # Normalize to tz-naive in all cases
                clean = sig_time_str.replace('Z', '').replace('+00:00', '')
                sig_dt = datetime.fromisoformat(clean)
            except Exception as e:
                logging.warning(f"Failed to parse time {sig_time_str}: {e}")
                continue
            
            # Has enough time passed since the signal to label it?
            if (current_dt - sig_dt).total_seconds() >= (self.look_forward_minutes * 60):
                
                target_end = sig_dt + timedelta(minutes=self.look_forward_minutes)
                
                # Slicing the dataframe - ensure index is also tz-naive for comparison
                try:
                    idx = history_df.index
                    # Normalize index if it's tz-aware, produce a plain numpy array of datetimes
                    if hasattr(idx, 'tz') and idx.tz is not None:
                        naive_idx = idx.tz_localize(None)
                    else:
                        naive_idx = idx
                    mask = (naive_idx > sig_dt) & (naive_idx <= target_end)
                    forward_window = history_df.loc[mask]
                except Exception as e:
                    logging.warning(f"Erro ao slicear historico: {e}")
                    continue

                if forward_window.empty:
                    # Not enough data (maybe a gap), just label with current known boundaries
                    max_p = trigger_price
                    min_p = trigger_price
                else:
                    max_p = forward_window['high'].max()
                    min_p = forward_window['low'].min()
                
                # Calculate percentages
                if direction == 'LONG':
                    win_pct = (max_p - trigger_price) / trigger_price
                    loss_pct = (min_p - trigger_price) / trigger_price
                elif direction == 'SHORT':
                    win_pct = (trigger_price - min_p) / trigger_price
                    loss_pct = (trigger_price - max_p) / trigger_price
                else:
                    win_pct = 0
                    loss_pct = 0
                
                # Update Database
                cursor.execute('''
                UPDATE signals 
                SET label_max_fwd_price = ?, label_min_fwd_price = ?, label_win_pct = ?, label_loss_pct = ?, is_labeled = 1
                WHERE id = ?
                ''', (max_p, min_p, win_pct, loss_pct, sig_id))
                
                logging.info(f"[MLDataCollector] 🏷️ Sinal {sig_id[:8]} classificado! Win Max: {win_pct*100:.2f}%, Drawdown Max: {loss_pct*100:.2f}%")
                
        self.conn.commit()

    def close(self):
        self.conn.close()
